### ISSUE TITLE
Small Documentation Change

### ISSUE THREAD

**Issue by sigfriedjk** [triplem/winston-config#4]
Great work on this -- short and saves me a few files.

Looks like the "logging" property wrapper isn't required if you use `fromJson` instead of `fromFile` (in fact it causes problems).  It is clear from the source and tests, but could update the documentation to make this clear? (The readme implies you always need "logging").

Let me know if you'd like me to make the change and submit a pull request.

**Comment by triplem** [comment]
Sorry for the really really late reply, but I definitly prefer "solutions" meaning pull requests instead of an issue only ;-)
