### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by jamesbibby** [triplem/winston-config#7]
Hey this looks pretty out of date.  Do you mind if I update the dependencies and add some support for promises via bluebird?

**Comment by jamesbibby** [comment]
I have submitted a pull request if you want to take a look

**Comment by colinbes** [comment]
Any chance of looking at @jamesbibby updates and accepting them?

**Comment by jamesbibby** [comment]
@colinbes they were merged.  Closing the issue

**Comment by colinbes** [comment]
Looks like issue is with npm which states 0.4.2 is latest issue with 
```
"dependencies": {
    "lodash": "~1.2.0"
  },
```
