### ISSUE TITLE
Publish current version

### ISSUE THREAD

**Issue by leider** [triplem/winston-config#9]
npm wants current versions (lodash)

**Comment by leider** [comment]
Hi,
this would be really great to eliminate deprecation warnings. Need help?

Cheers,
der leider

**Comment by triplem** [comment]
Thanks for the reminder. I just published the latest version. Hope that it is working as expected.

**Comment by leider** [comment]
Thanks. BTW there are Even newer Deps available. Would be great if you do a clean "npm install", check the messages and then repeat with an npm outdated

**Comment by triplem** [comment]
Should be fine with version 0.5.1.

Please try and report back. I will close this issue in a couple of days, if I do not hear anything.
